/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.firefuel;

import com.bean.MovimientosDetallesBean;
import com.controllers.NovusConstante;
import com.controllers.NovusUtils;
import com.dao.MovimientosDao;
import java.text.DecimalFormat;

/**
 *
 * @author usuario
 */
public class CategoriaProductoListItem extends javax.swing.JPanel {

    /**
     * Creates new form CategoriaProductoListItem
     */
    StoreViewController pedido;
    KCOViewController pedidoKCO;
    MovimientosDetallesBean producto;
    DecimalFormat df = new DecimalFormat(NovusConstante.FORMAT_MONEY);
    boolean ventaCombustibleMarcada = false;
    boolean productoYaFueAgregado = false;
    MovimientosDao mdao = new MovimientosDao();
    
    public CategoriaProductoListItem() {
        initComponents();
    }
    
    public CategoriaProductoListItem(MovimientosDetallesBean producto, StoreViewController pedido, boolean ventaCombustibleMarcada) {
        initComponents();
        this.producto = producto;
        this.pedido = pedido;
        this.ventaCombustibleMarcada = ventaCombustibleMarcada;
        this.init();
    }
    
    public CategoriaProductoListItem(MovimientosDetallesBean producto, StoreViewController pedido, boolean ventaCombustibleMarcada, boolean productoYaFueAgregado) {
        initComponents();
        this.producto = producto;
        this.pedido = pedido;
        this.ventaCombustibleMarcada = ventaCombustibleMarcada;
        this.productoYaFueAgregado = productoYaFueAgregado;
        this.init();
    }
    
    public CategoriaProductoListItem(MovimientosDetallesBean producto, StoreViewController pedido) {
        initComponents();
        this.producto = producto;
        this.pedido = pedido;
        this.init();
    }
    
    public CategoriaProductoListItem(MovimientosDetallesBean producto, KCOViewController pedido, boolean ventaCombustibleMarcada) {
        initComponents();
        this.producto = producto;
        this.pedidoKCO = pedido;
        this.ventaCombustibleMarcada = ventaCombustibleMarcada;
        this.init();
    }
    
    public CategoriaProductoListItem(MovimientosDetallesBean producto, KCOViewController pedido, boolean ventaCombustibleMarcada, boolean productoYaFueAgregado) {
        initComponents();
        this.producto = producto;
        this.pedidoKCO = pedido;
        this.ventaCombustibleMarcada = ventaCombustibleMarcada;
        this.productoYaFueAgregado = productoYaFueAgregado;
        this.init();
    }
    
    public CategoriaProductoListItem(MovimientosDetallesBean producto, KCOViewController pedido) {
        initComponents();
        this.producto = producto;
        this.pedidoKCO = pedido;
        this.init();
    }
    
    void init() {
        NovusUtils.ajusteFuente(this.getComponents(), NovusConstante.EXTRABOLD);
        jLabel1.setText("<html>" + producto.getDescripcion() + "</html>");
        jLabel3.setText("$ " + df.format(producto.getPrecio()));
        jLabel6.setText(producto.getPlu());
        if (this.productoYaFueAgregado) {
            this.desactivarBotonAgregar();
        }
    }
    
    void desactivarBotonAgregar() {
        this.jLabel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(400, 80));
        setMinimumSize(new java.awt.Dimension(400, 80));
        setName(""); // NOI18N
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel1.setText("<html>NOMBRE DEL PRODUCTO CON DESCRIPCIÓN LARGA</html>");
        add(jLabel1);
        jLabel1.setBounds(10, 0, 510, 40);

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(186, 12, 47));
        jLabel3.setText("$");
        add(jLabel3);
        jLabel3.setBounds(330, 40, 170, 20);

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("PRECIO:");
        add(jLabel4);
        jLabel4.setBounds(260, 40, 80, 20);

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 8)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/firefuel/resources/addProducto.png"))); // NOI18N
        jLabel2.setText("AGREGAR");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        add(jLabel2);
        jLabel2.setBounds(504, 0, 50, 65);

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("PLU:");
        add(jLabel5);
        jLabel5.setBounds(10, 40, 40, 20);

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(186, 12, 47));
        jLabel6.setText("0000");
        add(jLabel6);
        jLabel6.setBounds(60, 40, 80, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        mostrarPanelTecladoBusqueda(false);
    }//GEN-LAST:event_formMouseReleased
    
    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel2MouseReleased
        NovusUtils.beep();
        mostrarPanelTecladoBusqueda(false);
        agregarProducto();
    }// GEN-LAST:event_jLabel2MouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    private void agregarProducto() {
        if (pedido != null) {
            if (this.ventaCombustibleMarcada) {
                pedido.agregarProducto("TECLADO", producto.getPlu(), producto);
                desactivarBotonAgregar();
            } else {
                pedido.agregarProducto("TECLADO", producto.getPlu(), null);
            }
        } else {
            
            if (this.ventaCombustibleMarcada) {
                pedidoKCO.agregarProducto("TECLADO", producto.getPlu(), producto);
                desactivarBotonAgregar();
            } else {
                
                float precio = mdao.getPrecioEspecial(producto.getPlu());
                if (precio != 0) {
                    jLabel3.setText("$ " + df.format(precio));
                }
                
                pedidoKCO.agregarProducto("TECLADO", producto.getPlu(), null);
            }
        }
    }
    
    public void mostrarPanelTecladoBusqueda(boolean visible) {
        if (pedidoKCO != null) {
            pedidoKCO.mostrarPanelTecladoBusqueda(visible);
        }
    }
}
