/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.firefuel;

import com.bean.MediosPagosBean;
import com.controllers.ClientWSAsync;
import com.controllers.NovusConstante;
import com.controllers.NovusUtils;
import com.dao.SetupDao;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import teclado.view.common.TecladoNumerico;

/**
 *
 * @author Devitech
 */
public class FacturaElectronicaCortesia extends javax.swing.JDialog {

    ArrayList<MediosPagosBean> mediosPagosDisponibles;
    ArrayList<MediosPagosBean> mediosPagoVenta = new ArrayList<>();
    boolean isNewVenta;
    boolean isFac = false;

    public FacturaElectronicaCortesia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        init();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    void init() {
        this.loadMediosPagos();
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CMBMedioPagos = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlteclado = new TecladoNumerico();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText(""); // NOI18N
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        CMBMedioPagos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CMBMedioPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMBMedioPagosActionPerformed(evt);
            }
        });
        jPanel1.add(CMBMedioPagos);
        CMBMedioPagos.setBounds(50, 130, 404, 63);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(50, 300, 400, 60);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("VALOR TRANSACCIÓN");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 270, 400, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("MEDIO DE PAGO");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 90, 400, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 170, 520, 470);
        getContentPane().add(pnlteclado);
        pnlteclado.setBounds(610, 170, 630, 470);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(
                new javax.swing.ImageIcon(getClass().getResource("/com/firefuel/resources/fnd_principal0.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CMBMedioPagosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CMBMedioPagosActionPerformed
        changeMedio();
    }// GEN-LAST:event_CMBMedioPagosActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTextField1KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JOptionPane.showMessageDialog(null, CMBMedioPagos.getSelectedItem());
        }
    }// GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    // /* Set the Nimbus look and feel */
    // //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    // /* If Nimbus (introduced in Java SE 6) is not available, stay with the
    // default look and feel.
    // * For details see
    // http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
    // */
    // try {
    // for (javax.swing.UIManager.LookAndFeelInfo info :
    // javax.swing.UIManager.getInstalledLookAndFeels()) {
    // if ("Nimbus".equals(info.getName())) {
    // javax.swing.UIManager.setLookAndFeel(info.getClassName());
    // break;
    // }
    // }
    // } catch (ClassNotFoundException ex) {
    // java.util.logging.Logger.getLogger(FacturaElectronicaCortesia.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (InstantiationException ex) {
    // java.util.logging.Logger.getLogger(FacturaElectronicaCortesia.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (IllegalAccessException ex) {
    // java.util.logging.Logger.getLogger(FacturaElectronicaCortesia.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    // java.util.logging.Logger.getLogger(FacturaElectronicaCortesia.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // }
    // //</editor-fold>
    //
    // /* Create and display the dialog */
    // java.awt.EventQueue.invokeLater(new Runnable() {
    // public void run() {
    // FacturaElectronicaCortesia dialog = new FacturaElectronicaCortesia(new
    // javax.swing.JFrame(), true);
    // dialog.addWindowListener(new java.awt.event.WindowAdapter() {
    // @Override
    // public void windowClosing(java.awt.event.WindowEvent e) {
    // System.exit(0);
    // }
    // });
    // dialog.setVisible(true);
    // }
    // });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CMBMedioPagos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pnlteclado;

    // End of variables declaration//GEN-END:variables
    private void loadMediosPagos() {
        SetupDao dao = new SetupDao();
        mediosPagosDisponibles = dao.getMediosPagos(false);
        if (mediosPagosDisponibles != null) {
            for (MediosPagosBean medio : mediosPagosDisponibles) {
                CMBMedioPagos.addItem(medio.getDescripcion().toUpperCase());
            }
        }
        if (!this.isNewVenta && !isFac) {
            JsonObject response = new JsonObject();
            JsonObject objMain = new JsonObject();

            TreeMap<String, String> header = new TreeMap<>();
            header.put("Content-Type", "application/json");
            ClientWSAsync ws = new ClientWSAsync("g", NovusConstante.SECURE_END_POINT_CAMBIO_MEDIOSPAGOS,
                    NovusConstante.POST, objMain, false, false, header);
            try {
                ws.start();
                ws.join();
                response = ws.getResponse();
                NovusUtils.printLn(response.toString());
            } catch (InterruptedException ex) {
                NovusUtils.printLn(ex.getMessage());
            }
            mediosPagoVenta.clear();
            if (response != null) {
                JsonArray data = response.get("data").getAsJsonArray();
                for (JsonElement arr : data) {
                    JsonObject json = arr.getAsJsonObject();
                    MediosPagosBean medio = new MediosPagosBean();
                    medio.setId(json.get("ct_medios_pagos_id").getAsLong());
                    medio.setDescripcion(json.get("descripcion").getAsString().toUpperCase());
                    medio.setRecibido(json.get("valor_recibido").getAsFloat());
                    medio.setCambio(json.get("valor_cambio").getAsFloat());
                    medio.setValor(json.get("valor_total").getAsFloat());
                    medio.setVoucher(json.get("numero_comprobante").getAsString());
                    mediosPagoVenta.add(medio);
                }
            }
        }
        this.resetFields();
        this.changeMedio();

    }

    private void changeMedio() {
        int index = CMBMedioPagos.getSelectedIndex();
        this.resetFields();
    }

    private void resetFields() {
        jTextField1.setText("");

    }
}
