/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.firefuel;

import com.WT2.loyalty.domain.entities.beans.FoundClient;
import com.WT2.loyalty.domain.entities.beans.IdentificationClient;
import com.bean.MovimientosBean;
import com.bean.MovimientosDetallesBean;
import com.controllers.NovusConstante;
import com.controllers.NovusUtils;
import com.facade.fidelizacion.ConsultarCliente;
import com.firefuel.components.panelesPersonalizados.ComboBox;
import com.firefuel.components.panelesPersonalizados.ScrollBar;
import com.google.gson.JsonObject;
import com.utils.enums.TipoDeDocumentos;
import com.utils.enums.TipoNegociosFidelizacion;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.text.DecimalFormat;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import teclado.view.common.TecladoNumerico;

/**
 *
 * @author Devitech
 */
public class FidelizacionKioscos extends javax.swing.JPanel {

    private MovimientosBean movimientosBean;
    private Runnable cerrar;
    DecimalFormat df = new DecimalFormat(NovusConstante.FORMAT_MONEY_WITHOUT_ZERO);
    Color activo = new Color(228, 30, 19);
    Color inactivo = new Color(229, 230, 232);
    private IdentificationClient datosCliente;
    private boolean negocio;

    public FidelizacionKioscos() {
        initComponents();
        init();
    }

    public FidelizacionKioscos(MovimientosBean movimientosBean, Runnable cerrar, boolean negocio) {
        this.movimientosBean = movimientosBean;
        this.cerrar = cerrar;
        this.negocio = negocio;
        initComponents();
        init();
    }

    private void init() {
        ComboBox comboBox = new ComboBox();
        TiposDocumentos.setUI(comboBox.createUI(TiposDocumentos));
        placeholder();
        inicializarVenta();
        recorrerProductos();
        personalizarScroll();
        cargarindentificaciones();
        iniciarTeclado();
    }

    public void setDatosCliente(IdentificationClient datosClienteResponse) {
        this.datosCliente = datosClienteResponse;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPadre = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        pnlPrincipalInfoVenta = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        informacionVenta = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelContenedor = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        consecutivo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ventaTotal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pnlPrincipalTeclado = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        panelRedondo1 = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        jLabel3 = new javax.swing.JLabel();
        pnlTeclado = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        panelRedondo2 = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        TiposDocumentos = new javax.swing.JComboBox<>();
        txtNumerodocumento = new javax.swing.JTextField();
        txtinfoCaracteres = new javax.swing.JLabel();
        btnConsultar = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        consultar = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        pnlInformacionRespuesta = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        infoResultado = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        txtNombreCliente = new javax.swing.JLabel();
        txtInfoCliente = new javax.swing.JLabel();
        cargando = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        jLabel5 = new javax.swing.JLabel();
        btnGuardarVenta = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        guardarVenta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPadre.setBackground(new java.awt.Color(229, 230, 232));
        pnlPadre.setName("pnlPadre"); // NOI18N
        pnlPadre.setRoundBottomLeft(30);
        pnlPadre.setRoundBottomRight(30);
        pnlPadre.setRoundTopLeft(30);
        pnlPadre.setRoundTopRight(30);
        pnlPadre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPrincipalInfoVenta.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipalInfoVenta.setName("pnlPrincipalInfoVenta"); // NOI18N
        pnlPrincipalInfoVenta.setLayout(new java.awt.CardLayout());

        informacionVenta.setBackground(new java.awt.Color(255, 255, 255));
        informacionVenta.setName("informacionVenta"); // NOI18N
        informacionVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        panelContenedor.setBackground(new java.awt.Color(229, 230, 232));
        panelContenedor.setName("panelContenedor"); // NOI18N
        panelContenedor.setLayout(new java.awt.GridLayout(0, 1, 5, 5));
        jScrollPane1.setViewportView(panelContenedor);

        informacionVenta.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 560, 300));

        consecutivo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        consecutivo.setForeground(new java.awt.Color(167, 25, 22));
        consecutivo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        consecutivo.setText("POS-1923");
        consecutivo.setName("consecutivo"); // NOI18N
        informacionVenta.add(consecutivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 280, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(103, 103, 102));
        jLabel4.setText("VENTA:");
        jLabel4.setName("jLabel4"); // NOI18N
        informacionVenta.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(103, 103, 102));
        jLabel6.setText("VENTA:");
        jLabel6.setName("jLabel6"); // NOI18N
        informacionVenta.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, 40));

        ventaTotal.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ventaTotal.setForeground(new java.awt.Color(167, 25, 22));
        ventaTotal.setText("$ 10.000");
        ventaTotal.setName("ventaTotal"); // NOI18N
        informacionVenta.add(ventaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 280, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(103, 103, 102));
        jLabel8.setText("PRODUCTO:");
        jLabel8.setName("jLabel8"); // NOI18N
        informacionVenta.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 180, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(103, 103, 102));
        jLabel9.setText("TOTAL:");
        jLabel9.setName("jLabel9"); // NOI18N
        informacionVenta.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(75, 74, 92));
        jLabel15.setText("Resumen de venta");
        jLabel15.setName("jLabel15"); // NOI18N
        informacionVenta.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 270, 40));

        pnlPrincipalInfoVenta.add(informacionVenta, "informacionVenta");

        pnlPrincipalTeclado.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipalTeclado.setName("pnlPrincipalTeclado"); // NOI18N
        pnlPrincipalTeclado.setLayout(null);

        panelRedondo1.setBackground(new java.awt.Color(228, 30, 19));
        panelRedondo1.setName("panelRedondo1"); // NOI18N
        panelRedondo1.setRoundBottomLeft(50);
        panelRedondo1.setRoundBottomRight(50);
        panelRedondo1.setRoundTopLeft(50);
        panelRedondo1.setRoundTopRight(50);
        panelRedondo1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setToolTipText("");
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        panelRedondo1.add(jLabel3);
        jLabel3.setBounds(2, 2, 36, 35);

        pnlPrincipalTeclado.add(panelRedondo1);
        panelRedondo1.setBounds(10, 10, 40, 40);

        pnlTeclado.setBackground(new java.awt.Color(255, 255, 255));
        pnlTeclado.setName("pnlTeclado"); // NOI18N
        pnlPrincipalTeclado.add(pnlTeclado);
        pnlTeclado.setBounds(10, 60, 550, 470);

        pnlPrincipalInfoVenta.add(pnlPrincipalTeclado, "teclado");

        pnlPadre.add(pnlPrincipalInfoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 580, 540));

        panelRedondo2.setBackground(new java.awt.Color(255, 255, 255));
        panelRedondo2.setName("panelRedondo2"); // NOI18N
        panelRedondo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TiposDocumentos.setBackground(new java.awt.Color(255, 255, 255));
        TiposDocumentos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TiposDocumentos.setBorder(new com.firefuel.components.panelesPersonalizados.BordesRedondos());
        TiposDocumentos.setName("TiposDocumentos"); // NOI18N
        TiposDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiposDocumentosActionPerformed(evt);
            }
        });
        panelRedondo2.add(TiposDocumentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 570, 64));

        txtNumerodocumento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtNumerodocumento.setBorder(new com.firefuel.components.panelesPersonalizados.BordesRedondos());
        txtNumerodocumento.setMargin(new java.awt.Insets(2, 10, 2, 10));
        txtNumerodocumento.setName("txtNumerodocumento"); // NOI18N
        txtNumerodocumento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumerodocumentoFocusGained(evt);
            }
        });
        txtNumerodocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNumerodocumentoMouseClicked(evt);
            }
        });
        txtNumerodocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumerodocumentoKeyTyped(evt);
            }
        });
        panelRedondo2.add(txtNumerodocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 570, 64));

        txtinfoCaracteres.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtinfoCaracteres.setForeground(new java.awt.Color(75, 74, 92));
        txtinfoCaracteres.setName("txtinfoCaracteres"); // NOI18N
        panelRedondo2.add(txtinfoCaracteres, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 340, 20));

        btnConsultar.setBackground(new java.awt.Color(229, 230, 232));
        btnConsultar.setName("btnConsultar"); // NOI18N
        btnConsultar.setRoundBottomLeft(20);
        btnConsultar.setRoundBottomRight(20);
        btnConsultar.setRoundTopLeft(20);
        btnConsultar.setRoundTopRight(20);
        btnConsultar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        consultar.setBackground(new java.awt.Color(229, 230, 232));
        consultar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        consultar.setForeground(new java.awt.Color(228, 30, 19));
        consultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        consultar.setText("CONSULTAR");
        consultar.setName("consultar"); // NOI18N
        consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultarMouseClicked(evt);
            }
        });
        btnConsultar.add(consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 64));

        panelRedondo2.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 455, 570, 64));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(75, 74, 92));
        jLabel12.setText("Acumular Puntos");
        jLabel12.setName("jLabel12"); // NOI18N
        panelRedondo2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 270, 40));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(75, 74, 92));
        lblTitulo.setText("CLIENTE");
        lblTitulo.setName("lblTitulo"); // NOI18N
        panelRedondo2.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 350, 40));

        pnlInformacionRespuesta.setBackground(new java.awt.Color(255, 255, 255));
        pnlInformacionRespuesta.setName("pnlInformacionRespuesta"); // NOI18N
        pnlInformacionRespuesta.setLayout(new java.awt.CardLayout());

        infoResultado.setBackground(new java.awt.Color(255, 255, 255));
        infoResultado.setName("infoResultado"); // NOI18N
        infoResultado.setLayout(null);

        txtNombreCliente.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        txtNombreCliente.setForeground(new java.awt.Color(75, 74, 92));
        txtNombreCliente.setName("txtNombreCliente"); // NOI18N
        infoResultado.add(txtNombreCliente);
        txtNombreCliente.setBounds(30, 0, 510, 40);

        txtInfoCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtInfoCliente.setForeground(new java.awt.Color(75, 74, 92));
        txtInfoCliente.setName("txtInfoCliente"); // NOI18N
        infoResultado.add(txtInfoCliente);
        txtInfoCliente.setBounds(30, 40, 490, 30);

        pnlInformacionRespuesta.add(infoResultado, "infoResultado");

        cargando.setBackground(new java.awt.Color(255, 255, 255));
        cargando.setName("cargando"); // NOI18N
        cargando.setLayout(null);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/firefuel/resources/cargando.gif"))); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        cargando.add(jLabel5);
        jLabel5.setBounds(10, 0, 170, 150);

        pnlInformacionRespuesta.add(cargando, "cargando");

        panelRedondo2.add(pnlInformacionRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 570, 160));

        pnlPadre.add(panelRedondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 590, 540));

        add(pnlPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1230, 580));

        btnGuardarVenta.setBackground(new java.awt.Color(229, 230, 232));
        btnGuardarVenta.setName("btnGuardarVenta"); // NOI18N
        btnGuardarVenta.setRoundBottomLeft(20);
        btnGuardarVenta.setRoundBottomRight(20);
        btnGuardarVenta.setRoundTopLeft(20);
        btnGuardarVenta.setRoundTopRight(20);
        btnGuardarVenta.setLayout(null);

        guardarVenta.setBackground(new java.awt.Color(255, 255, 255));
        guardarVenta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        guardarVenta.setForeground(new java.awt.Color(228, 30, 19));
        guardarVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guardarVenta.setText("CONTINUAR CON LA VENTA");
        guardarVenta.setName("guardarVenta"); // NOI18N
        guardarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarVentaMouseClicked(evt);
            }
        });
        btnGuardarVenta.add(guardarVenta);
        guardarVenta.setBounds(0, 0, 430, 60);

        add(btnGuardarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 720, 430, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/firefuel/resources/btn_atras.png"))); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 70, 70));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CONFIRMACIÓN DE VENTA");
        jLabel7.setName("jLabel7"); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 690, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/firefuel/resources/fndRumbo.png"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));
    }// </editor-fold>//GEN-END:initComponents

    private void TiposDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiposDocumentosActionPerformed
        obtenerDocumento();
    }//GEN-LAST:event_TiposDocumentosActionPerformed

    private void txtNumerodocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumerodocumentoKeyTyped
        boolean completado = NovusUtils.validacionesCampos(evt, txtNumerodocumento, 20, txtinfoCaracteres, "[0-9]", 18, 6, Color.RED);
        botonActivo(btnConsultar, completado, consultar);
    }//GEN-LAST:event_txtNumerodocumentoKeyTyped

    private void consultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarMouseClicked
        
        if (btnConsultar.getBackground().equals(activo)) {
        //AQUI PASO 2 dos de fidelizacion KIOSCO 
        //Consultar cliente
            consultarCliente();
        }
    }//GEN-LAST:event_consultarMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        cerrar();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtNumerodocumentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumerodocumentoFocusGained
        NovusUtils.deshabilitarCopiarPegar(txtNumerodocumento);
    }//GEN-LAST:event_txtNumerodocumentoFocusGained

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        cambiarPanel(pnlPrincipalInfoVenta, "informacionVenta");
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtNumerodocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumerodocumentoMouseClicked
        cambiarPanel(pnlPrincipalInfoVenta, "teclado");
    }//GEN-LAST:event_txtNumerodocumentoMouseClicked

    private void guardarVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarVentaMouseClicked
        if (btnGuardarVenta.getBackground().equals(activo)) {
            continuarConLaVenta();
        }

    }//GEN-LAST:event_guardarVentaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> TiposDocumentos;
    private com.firefuel.components.panelesPersonalizados.PanelRedondo btnConsultar;
    private com.firefuel.components.panelesPersonalizados.PanelRedondo btnGuardarVenta;
    private com.firefuel.components.panelesPersonalizados.PanelRedondo cargando;
    private javax.swing.JLabel consecutivo;
    private javax.swing.JLabel consultar;
    private javax.swing.JLabel guardarVenta;
    private com.firefuel.components.panelesPersonalizados.PanelRedondo infoResultado;
    private com.firefuel.components.panelesPersonalizados.PanelRedondo informacionVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private com.firefuel.components.panelesPersonalizados.PanelRedondo panelContenedor;
    private com.firefuel.components.panelesPersonalizados.PanelRedondo panelRedondo1;
    private com.firefuel.components.panelesPersonalizados.PanelRedondo panelRedondo2;
    private com.firefuel.components.panelesPersonalizados.PanelRedondo pnlInformacionRespuesta;
    private com.firefuel.components.panelesPersonalizados.PanelRedondo pnlPadre;
    private com.firefuel.components.panelesPersonalizados.PanelRedondo pnlPrincipalInfoVenta;
    private com.firefuel.components.panelesPersonalizados.PanelRedondo pnlPrincipalTeclado;
    private com.firefuel.components.panelesPersonalizados.PanelRedondo pnlTeclado;
    private javax.swing.JLabel txtInfoCliente;
    private javax.swing.JLabel txtNombreCliente;
    private javax.swing.JTextField txtNumerodocumento;
    private javax.swing.JLabel txtinfoCaracteres;
    private javax.swing.JLabel ventaTotal;
    // End of variables declaration//GEN-END:variables

    private void placeholder() {
        TextPrompt placeholder = new TextPrompt("NÚMERO DE DOCUMENTO", txtNumerodocumento);
        placeholder.changeAlpha(0.75f);
    }

    private void recorrerProductos() {
        if (movimientosBean != null) {
            for (Map.Entry<Long, MovimientosDetallesBean> entry : movimientosBean.getDetalles().entrySet()) {
                MovimientosDetallesBean detalle = entry.getValue();
                ItemProductos itemProductos = new ItemProductos();
                itemProductos.nombreProducto.setText(detalle.getDescripcion());
                itemProductos.cantidad.setText(Math.round(detalle.getCantidadUnidad()) + "");
                float precio = detalle.getPrecio() * detalle.getCantidadUnidad();
                itemProductos.precio.setText(df.format(precio));
                itemProductos.extra.setText("Producto Nro " + detalle.getId() + " P/U " + df.format(detalle.getPrecio()));
                itemProductos.producto.setPreferredSize(new Dimension(540, 60));
                panelContenedor.add(itemProductos.producto);
            }
        }
    }

    private void inicializarVenta() {
        ventaTotal.setText("$ " + df.format(movimientosBean.getVentaTotal()));
        consecutivo.setText(movimientosBean.getConsecutivo().getPrefijo() + " - " + movimientosBean.getConsecutivo().getConsecutivo_actual());
    }

    private void personalizarScroll() {
        ScrollBar scrollBar = new ScrollBar();
        scrollBar.scroll(jScrollPane1);
    }

    private void cargarindentificaciones() {
        TiposDocumentos.addItem("TIPO DE DOCUMENTO");
        TiposDocumentos.addItem("CEDULA DE CIUDADANIA");
        TiposDocumentos.addItem("CEDULA DE EXTRANJERÍA");
        TiposDocumentos.setSelectedIndex(1);
    }

    private String obtenerDocumento() {
        TipoDeDocumentos tipos = new TipoDeDocumentos(TiposDocumentos.getSelectedItem().toString());
        return tipos.obtenerTiposDocumentos();
    }

    private void botonActivo(JPanel boton, boolean activar, JLabel titulo) {
        boton.setBackground(activar ? activo : inactivo);
        titulo.setForeground(activar ? Color.WHITE : activo);
    }

    private void consultarCliente() {
        lblTitulo.setText("ESPERE UN MOMENTO");
        cambiarPanel(pnlInformacionRespuesta, "cargando");
        Thread response = new Thread() {
            @Override
            public void run() {
                ConsultarCliente consultarCliente = new ConsultarCliente();
                String documentNumber = txtNumerodocumento.getText();
                String tipoNegocio = negocio ? TipoNegociosFidelizacion.CANASTILLA.getTipoNegocio() : TipoNegociosFidelizacion.KIOSCO.getTipoNegocio();
                FoundClient respuesta = consultarCliente.execute(obtenerDocumento(),documentNumber , tipoNegocio);
                respuesta.getDatosCliente().getCustomer().setNumeroIdentificacion(documentNumber);
                pintarRespuesta(respuesta);
                cambiarPanel(pnlPrincipalInfoVenta, "informacionVenta");
            }
        };
        response.start();
    }

    private void pintarRespuesta(FoundClient respuesta) {
        switch (respuesta.getStatus()) {
            case 20000:
            case 200:
            case 600:
                lblTitulo.setText("CLIENTE");
                txtNombreCliente.setText(respuesta.getNombreCliente());
                txtInfoCliente.setText(respuesta.getAdicional());
                setDatosCliente(respuesta.getDatosCliente().getCustomer());
                botonActivo(btnGuardarVenta, respuesta.isExisteClient(), guardarVenta);
                break;
            case 400:
                lblTitulo.setText("CLIENTE");
                setDatosCliente(null);
                txtNombreCliente.setText(respuesta.getMensaje());
                botonActivo(btnGuardarVenta, false, guardarVenta);
                break;
            default:
                lblTitulo.setText("CLIENTE");
                setDatosCliente(null);
                txtNombreCliente.setText(respuesta.getMensaje());
                botonActivo(btnGuardarVenta, false, guardarVenta);
        }
        cambiarPanel(pnlInformacionRespuesta, "infoResultado");
    }

    private void cerrar() {
        if (cerrar != null) {
            cerrar.run();
        }
    }

    private void iniciarTeclado() {
        TecladoNumerico tecladoNumerico = new TecladoNumerico();
        tecladoNumerico.setPreferredSize(new Dimension(550, 470));
        pnlTeclado.add(tecladoNumerico, new AbsoluteConstraints(10, 80, 550, 470));
    }

    private void cambiarPanel(JPanel panel, String nombre) {
        CardLayout card = (CardLayout) panel.getLayout();
        card.show(panel, nombre);
    }

    private void continuarConLaVenta() {
        StoreConfirmarViewController.setDatosCliente(datosCliente);
        cerrar();
    }
}
