/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.firefuel;

/**
 *
 * @author Devitech
 */
public class ItemProductos extends javax.swing.JPanel {

    /**
     * Creates new form ItemProductos
     */
    public ItemProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        producto = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        precio = new javax.swing.JLabel();
        extra = new javax.swing.JLabel();
        nombreProducto = new javax.swing.JLabel();
        cantidad = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        producto.setBackground(new java.awt.Color(255, 255, 255));
        producto.setName("producto"); // NOI18N
        producto.setRoundBottomLeft(15);
        producto.setRoundBottomRight(15);
        producto.setRoundTopLeft(15);
        producto.setRoundTopRight(15);
        producto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        precio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        precio.setForeground(new java.awt.Color(167, 25, 22));
        precio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precio.setText("$20.000.000");
        precio.setName("precio"); // NOI18N
        producto.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 15, 160, 30));

        extra.setForeground(new java.awt.Color(102, 102, 102));
        extra.setText("Producto Nro: 1453 - PLU: 324");
        extra.setName("extra"); // NOI18N
        producto.add(extra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 34, 250, 20));

        nombreProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreProducto.setForeground(new java.awt.Color(60, 63, 65));
        nombreProducto.setText("PAPITAS MARGARITA LIMON");
        nombreProducto.setName("nombreProducto"); // NOI18N
        producto.add(nombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 240, 30));

        cantidad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cantidad.setForeground(new java.awt.Color(60, 63, 65));
        cantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidad.setText("1234423");
        cantidad.setName("cantidad"); // NOI18N
        producto.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 15, 120, 30));

        add(producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 60));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel cantidad;
    public javax.swing.JLabel extra;
    public javax.swing.JLabel nombreProducto;
    public javax.swing.JLabel precio;
    public com.firefuel.components.panelesPersonalizados.PanelRedondo producto;
    // End of variables declaration//GEN-END:variables
}
