/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.firefuel;

import com.bean.MedioIdentificacionBean;
import com.controllers.NovusUtils;

/**
 *
 * @author USUARIO
 */
public class item_panel extends javax.swing.JPanel {

    private final MedioIdentificacionBean model;
    RumboView parentRumboView = null;
    RecuperacionVentaView parentRecuperacionView = null;
    boolean enabled;

    public item_panel(RumboView parentRumboView, MedioIdentificacionBean model, boolean enabled) {
        initComponents();
        this.model = model;
        this.enabled = enabled;
        this.parentRumboView = parentRumboView;
        this.init();
    }

    public item_panel(RecuperacionVentaView parentRumboView, MedioIdentificacionBean model, boolean enabled) {
        initComponents();
        this.model = model;
        this.enabled = enabled;
        this.parentRecuperacionView = parentRumboView;
        this.init();
    }

    private void init() {
        this.loadComponent();
    }

    void renderIdentifierData() {
        MedioIdentificacionBean mid = this.getModel();
        if (mid != null) {
            this.lbl_identifier_name.setText("<html>" + mid.getDescripcion() + "</html>");
            try {
                this.lbl_identifier_image.setIcon(new javax.swing.ImageIcon(
                        getClass().getResource("/com/firefuel/resources/" + mid.getUrlImagen()))); // NOI18N
            } catch (Exception e) {
                NovusUtils.printLn(e.getMessage());
            }
        }
    }

    void handleClick() {
        if (parentRumboView != null) {
            if (getModel().getId() == RumboView.APP_RUMBO_ID) {
                mostrarIngresoPlacaApp();
            } else {
                RumboView.APP_RUMBO = false;
                parentRumboView.listenIdentifiersClick(getModel());
            }
        } else {
            parentRecuperacionView.listenIdentifiersClick(getModel());
        }
    }

    void mostrarIngresoPlacaApp() {
        RumboView.APP_RUMBO = true;
        RumboView.panelActualFlujoApp = RumboView.PNL_IDENTIFIER_LISTEN;
        parentRumboView.loadInputsIdentifierPanel();
        parentRumboView.mostrarPanel(RumboView.PNL_IDENTIFIER_LISTEN);
        RumboView.txt_placa_input.requestFocus();
    }

    void loadComponent() {
        this.renderIdentifierData();
    }

    public MedioIdentificacionBean getModel() {
        return this.model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_identifier_name = new javax.swing.JLabel();
        lbl_identifier_image = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(185, 370));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(185, 370));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(null);

        lbl_identifier_name.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_identifier_name.setForeground(new java.awt.Color(75, 74, 92));
        lbl_identifier_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_identifier_name.setText("NOMBRE IDENTIFICADOR");
        lbl_identifier_name.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_identifier_name.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lbl_identifier_name);
        lbl_identifier_name.setBounds(10, 230, 180, 70);

        lbl_identifier_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_identifier_image.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lbl_identifier_image);
        lbl_identifier_image.setBounds(-8, 0, 206, 260);

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/firefuel/resources/item_identificadores.png"))); // NOI18N
        background.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(background);
        background.setBounds(0, -2, 200, 390);
        background.getAccessibleContext().setAccessibleName("background");
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.handleClick();
    }//GEN-LAST:event_formMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased

    }//GEN-LAST:event_formMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel lbl_identifier_image;
    private javax.swing.JLabel lbl_identifier_name;
    // End of variables declaration//GEN-END:variables
}
