/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.firefuel;

import com.controllers.NovusConstante;
import com.controllers.NovusUtils;

/**
 *
 * @author Admin
 */
public class NotifyItemView extends javax.swing.JPanel {

    /**
     * Creates new form NotifyItemView
     */
    public NotifyItemView() {
        initComponents();
        this.init();
    }

    void init() {
        NovusUtils.ajusteFuente(this.getComponents(), NovusConstante.EXTRABOLD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTituloNotificacion = new javax.swing.JLabel();
        jFechaNotificacion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jTituloNotificacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTituloNotificacion.setText("BLOQUEO DE SURTIDOR");
        add(jTituloNotificacion);
        jTituloNotificacion.setBounds(20, 10, 900, 50);

        jFechaNotificacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jFechaNotificacion.setForeground(new java.awt.Color(186, 12, 47));
        jFechaNotificacion.setText("10/02/21 16:30:00");
        add(jFechaNotificacion);
        jFechaNotificacion.setBounds(950, 10, 190, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/firefuel/resources/fndContenidoNotify.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 1, 1170, 70);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jFechaNotificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jTituloNotificacion;
    // End of variables declaration//GEN-END:variables
}
