/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.firefuel;

import com.controllers.NovusConstante;
import com.firefuel.componentes.notificaciones.error.RenderizacionError;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author Devitech
 */
public class NotificacionesErrores extends javax.swing.JDialog {

    /**
     * Creates new form NotificacionesErrores
     */
    JsonArray notificaiconesErrores = null;
    InfoViewController info;
    RenderizacionError renderizacionError = new RenderizacionError(this);
    Color activo = new Color(204, 0, 0);
    Color inactivo = new Color(244, 244, 244);

    public NotificacionesErrores(InfoViewController info, JsonArray notificacionesErrores) {
        super(info, true);
        this.info = info;
        this.notificaiconesErrores = notificacionesErrores;
        initComponents();
        init();
    }

    private void init() {
        if (NovusConstante.BASE_DE_dATOS_ACTIVA) {
            renderizacionError.activarYDesactivar(btnHistorico, HIstorico);
            renderizacionError.mostrarNotificaionesError(true, null);
        } else {
            renderizacionError.activarYDesactivar(btnReciente, lblReciente);
            renderizacionError.mostrarNotificaionesError(false, this.notificaiconesErrores);

        }
        renderizacionError.scrollPanelPerosonalizado(fechasScroll);
        this.fechasScroll.setBorder(BorderFactory.createEmptyBorder(10, 0, 10, 0));
        renderizacionError.scrollPanelPerosonalizado(scrollContenedorInformacion);
        setLocationRelativeTo(null);
        this.setBackground(new Color(0, 0, 0, 0.6f));
        notificacionesErrores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRedondo1 = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        scrollContenedorInformacion = new javax.swing.JScrollPane();
        pnlInformacionContenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        jLabel2 = new javax.swing.JLabel();
        fechasScroll = new javax.swing.JScrollPane();
        pnlFechas = new javax.swing.JPanel();
        panelRedondo3 = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        lblCerrar = new javax.swing.JLabel();
        btnReciente = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        lblReciente = new javax.swing.JLabel();
        btnHistorico = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        HIstorico = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1280, 800));
        getContentPane().setLayout(null);

        panelRedondo1.setBackground(new java.awt.Color(255, 255, 255));
        panelRedondo1.setName("panelRedondo1"); // NOI18N
        panelRedondo1.setRoundBottomLeft(30);
        panelRedondo1.setRoundBottomRight(30);
        panelRedondo1.setRoundTopLeft(30);
        panelRedondo1.setRoundTopRight(30);
        panelRedondo1.setLayout(null);

        scrollContenedorInformacion.setBorder(null);
        scrollContenedorInformacion.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollContenedorInformacion.setName("scrollContenedorInformacion"); // NOI18N

        pnlInformacionContenedor.setBackground(new java.awt.Color(255, 255, 255));
        pnlInformacionContenedor.setName("pnlInformacionContenedor"); // NOI18N
        pnlInformacionContenedor.setLayout(new javax.swing.BoxLayout(pnlInformacionContenedor, javax.swing.BoxLayout.PAGE_AXIS));
        scrollContenedorInformacion.setViewportView(pnlInformacionContenedor);

        panelRedondo1.add(scrollContenedorInformacion);
        scrollContenedorInformacion.setBounds(440, 107, 635, 470);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(167, 25, 22));
        jLabel1.setText("NOTIFICACIONES");
        jLabel1.setName("jLabel1"); // NOI18N
        panelRedondo1.add(jLabel1);
        jLabel1.setBounds(41, 34, 335, 50);

        btnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrar.setName("btnCerrar"); // NOI18N
        btnCerrar.setRoundBottomLeft(100);
        btnCerrar.setRoundBottomRight(100);
        btnCerrar.setRoundTopLeft(100);
        btnCerrar.setRoundTopRight(100);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout btnCerrarLayout = new javax.swing.GroupLayout(btnCerrar);
        btnCerrar.setLayout(btnCerrarLayout);
        btnCerrarLayout.setHorizontalGroup(
            btnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        btnCerrarLayout.setVerticalGroup(
            btnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelRedondo1.add(btnCerrar);
        btnCerrar.setBounds(1035, 40, 40, 40);

        fechasScroll.setBorder(null);
        fechasScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        fechasScroll.setName("fechasScroll"); // NOI18N

        pnlFechas.setBackground(new java.awt.Color(255, 255, 255));
        pnlFechas.setMinimumSize(new java.awt.Dimension(370, 472));
        pnlFechas.setName("pnlFechas"); // NOI18N
        pnlFechas.setPreferredSize(new java.awt.Dimension(370, 430));
        fechasScroll.setViewportView(pnlFechas);

        panelRedondo1.add(fechasScroll);
        fechasScroll.setBounds(25, 149, 370, 430);

        panelRedondo3.setBackground(new java.awt.Color(204, 0, 0));
        panelRedondo3.setName("panelRedondo3"); // NOI18N
        panelRedondo3.setRoundBottomLeft(30);
        panelRedondo3.setRoundBottomRight(30);
        panelRedondo3.setRoundTopLeft(30);
        panelRedondo3.setRoundTopRight(30);
        panelRedondo3.setLayout(null);

        lblCerrar.setBackground(new java.awt.Color(255, 255, 255));
        lblCerrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCerrar.setText("  CERRAR");
        lblCerrar.setToolTipText("");
        lblCerrar.setName("lblCerrar"); // NOI18N
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        panelRedondo3.add(lblCerrar);
        lblCerrar.setBounds(2, 4, 220, 40);

        panelRedondo1.add(panelRedondo3);
        panelRedondo3.setBounds(860, 35, 220, 50);

        btnReciente.setBackground(new java.awt.Color(204, 0, 0));
        btnReciente.setName("btnReciente"); // NOI18N
        btnReciente.setRoundBottomLeft(30);
        btnReciente.setRoundBottomRight(30);
        btnReciente.setRoundTopLeft(30);
        btnReciente.setRoundTopRight(30);
        btnReciente.setLayout(null);

        lblReciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblReciente.setForeground(new java.awt.Color(255, 255, 255));
        lblReciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReciente.setText("BASE DE DATOS");
        lblReciente.setName("lblReciente"); // NOI18N
        lblReciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRecienteMouseClicked(evt);
            }
        });
        btnReciente.add(lblReciente);
        lblReciente.setBounds(2, 0, 167, 49);

        panelRedondo1.add(btnReciente);
        btnReciente.setBounds(30, 90, 170, 50);

        btnHistorico.setBackground(new java.awt.Color(244, 244, 244));
        btnHistorico.setName("btnHistorico"); // NOI18N
        btnHistorico.setRoundBottomLeft(30);
        btnHistorico.setRoundBottomRight(30);
        btnHistorico.setRoundTopLeft(30);
        btnHistorico.setRoundTopRight(30);
        btnHistorico.setLayout(null);

        HIstorico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        HIstorico.setForeground(new java.awt.Color(51, 51, 51));
        HIstorico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HIstorico.setText("GENERALES");
        HIstorico.setName("HIstorico"); // NOI18N
        HIstorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HIstoricoMouseClicked(evt);
            }
        });
        btnHistorico.add(HIstorico);
        HIstorico.setBounds(2, 0, 167, 49);

        panelRedondo1.add(btnHistorico);
        btnHistorico.setBounds(210, 90, 170, 50);

        getContentPane().add(panelRedondo1);
        panelRedondo1.setBounds(80, 80, 1100, 627);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        InfoViewController.NotificadorNotificacionesError = null;
        this.dispose();
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblRecienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecienteMouseClicked
        if (btnReciente.getBackground().equals(activo)) {
            renderizacionError.activarYDesactivar(btnReciente, lblReciente);
            renderizacionError.mostrarNotificaionesError(false, this.notificaiconesErrores);
        }

    }//GEN-LAST:event_lblRecienteMouseClicked

    private void HIstoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HIstoricoMouseClicked
        if (btnHistorico.getBackground().equals(activo)) {
            cargar();
        }
    }//GEN-LAST:event_HIstoricoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel HIstorico;
    private com.firefuel.components.panelesPersonalizados.PanelRedondo btnCerrar;
    public com.firefuel.components.panelesPersonalizados.PanelRedondo btnHistorico;
    public com.firefuel.components.panelesPersonalizados.PanelRedondo btnReciente;
    public javax.swing.JScrollPane fechasScroll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCerrar;
    public javax.swing.JLabel lblReciente;
    private com.firefuel.components.panelesPersonalizados.PanelRedondo panelRedondo1;
    private com.firefuel.components.panelesPersonalizados.PanelRedondo panelRedondo3;
    public javax.swing.JPanel pnlFechas;
    public javax.swing.JPanel pnlInformacionContenedor;
    public javax.swing.JScrollPane scrollContenedorInformacion;
    // End of variables declaration//GEN-END:variables
    private void cargar() {
        renderizacionError.activarYDesactivar(btnHistorico, HIstorico);
        renderizacionError.mostrarNotificaionesError(true, null);
    }

    private void notificacionesErrores() {
        InfoViewController.NotificadorNotificacionesError = (JsonObject data) -> {
            if (NovusConstante.BASE_DE_dATOS_ACTIVA) {
                this.notificaiconesErrores = data.get("data").getAsJsonArray();
            } else {
                if (data.get("data").getAsJsonArray().size() > 0) {
                    this.notificaiconesErrores = data.get("data").getAsJsonArray();
                }
            }
            notificaiconesErrores.forEach((element) -> {
                JsonObject objData = element.getAsJsonObject();
                validarData(objData);
            });
            if (NovusConstante.BASE_DE_dATOS_ACTIVA) {
                renderizacionError.activarYDesactivar(btnHistorico, HIstorico);
                renderizacionError.mostrarNotificaionesError(true, null);
            } else {
                renderizacionError.activarYDesactivar(btnReciente, lblReciente);
                renderizacionError.mostrarNotificaionesError(false, this.notificaiconesErrores);
            }

        };
    }

    private void validarData(JsonObject objData) {
        if (objData.get("eventComponent").getAsString().toUpperCase().equals("DATABASE")) {
            NovusConstante.setEstadoDeLaBaseDeDatos(objData.get("eventStatus").getAsString().toUpperCase().equals("RESUELTA"));
        }
        
        if (objData.get("eventComponentProcess").getAsString().toUpperCase().equals("CORE__AUTODIAGNOSTICO")) {
            if (objData.get("eventStatus").getAsString().toUpperCase().equals("RESUELTA")){
                NovusConstante.setDataAutoDiagnosticoSurtidor(new JsonArray());
            }else{
                JsonArray data = new JsonArray();
                data.add(objData);
                NovusConstante.setDataAutoDiagnosticoSurtidor(data);
            }
        }
        
        if (objData.get("eventComponentProcess").getAsString().toUpperCase().equals("CORE__MAPEO_SURTIDOR")) {
            if (objData.get("eventStatus").getAsString().toUpperCase().equals("RESUELTA")){
                NovusConstante.setDataMapeoSurtidor(new JsonArray());
            }else{
                JsonArray data = new JsonArray();
                data.add(objData);
                NovusConstante.setDataMapeoSurtidor(data);
            }
        }
    }

}
