/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.firefuel;

/**
 *
 * @author proyectos
 */
public class PanelItemVenta extends javax.swing.JPanel {

    /**
     * Creates new form PanelItemVenta
     */
    public PanelItemVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_venta = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        pnl_venta.setBackground(new java.awt.Color(255, 255, 255));
        pnl_venta.setForeground(new java.awt.Color(204, 0, 0));
        pnl_venta.setOpaque(false);
        pnl_venta.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MAGUERA");
        pnl_venta.add(jLabel4);
        jLabel4.setBounds(679, 1, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("1");
        pnl_venta.add(jLabel3);
        jLabel3.setBounds(750, 2, 150, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("OSVALDO DE JESUS ALTAN MARTINEZ");
        pnl_venta.add(jLabel6);
        jLabel6.setBounds(33, 60, 350, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PROMOTOR");
        pnl_venta.add(jLabel5);
        jLabel5.setBounds(10, 40, 133, 19);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("GASOLINA CORRIENTE 10% OXIGENADA");
        pnl_venta.add(jLabel7);
        jLabel7.setBounds(33, 120, 420, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PRODUCTO");
        pnl_venta.add(jLabel8);
        jLabel8.setBounds(3, 100, 140, 19);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("RECIBO");
        pnl_venta.add(jLabel9);
        jLabel9.setBounds(16, 1, 99, 31);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("000000000000");
        pnl_venta.add(jLabel10);
        jLabel10.setBounds(121, 0, 179, 32);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("HORA");
        pnl_venta.add(jLabel11);
        jLabel11.setBounds(909, 0, 350, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("10:00 AM");
        pnl_venta.add(jLabel12);
        jLabel12.setBounds(910, 30, 350, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("PLACA");
        pnl_venta.add(jLabel13);
        jLabel13.setBounds(910, 88, 350, 22);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("ABC123");
        pnl_venta.add(jLabel14);
        jLabel14.setBounds(1010, 110, 150, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("CANTIDAD");
        pnl_venta.add(jLabel15);
        jLabel15.setBounds(560, 40, 350, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("100.002 GL");
        pnl_venta.add(jLabel16);
        jLabel16.setBounds(560, 70, 350, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("TOTAL VENTA");
        pnl_venta.add(jLabel17);
        jLabel17.setBounds(560, 100, 350, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("$500.000.000");
        pnl_venta.add(jLabel18);
        jLabel18.setBounds(560, 130, 350, 20);
        pnl_venta.add(jSeparator1);
        jSeparator1.setBounds(0, 30, 910, 2);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnl_venta.add(jSeparator2);
        jSeparator2.setBounds(1248, 0, 2, 160);

        jSeparator3.setPreferredSize(new java.awt.Dimension(1230, 10));
        pnl_venta.add(jSeparator3);
        jSeparator3.setBounds(0, 160, 1250, 10);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnl_venta.add(jSeparator4);
        jSeparator4.setBounds(910, 0, 10, 160);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnl_venta.add(jSeparator5);
        jSeparator5.setBounds(0, 0, 10, 160);

        jSeparator6.setPreferredSize(new java.awt.Dimension(1230, 10));
        pnl_venta.add(jSeparator6);
        jSeparator6.setBounds(0, 0, 1250, 10);

        add(pnl_venta);
        pnl_venta.setBounds(0, 0, 1260, 170);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel pnl_venta;
    // End of variables declaration//GEN-END:variables
}
