/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.firefuel;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Devitech
 */
public class ProcesosFEyFidelizacion extends javax.swing.JPanel {

    /**
     * Creates new form ProcesosFEyFidelizacion
     */
    public ProcesosFEyFidelizacion() {
        initComponents();
        ImageIcon img = new ImageIcon(getClass().getResource("/com/firefuel/resources/marca-de-verificacion (4).png"));
        Icon icono = new ImageIcon(img.getImage().getScaledInstance(lblIcono.getWidth(), lblIcono.getHeight(), Image.SCALE_DEFAULT));
        lblIcono.setIcon(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProceso = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        lblOperacion = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();

        setLayout(null);

        panelProceso.setBackground(new java.awt.Color(255, 255, 255));
        panelProceso.setName("panelProceso"); // NOI18N
        panelProceso.setRoundBottomLeft(50);
        panelProceso.setRoundBottomRight(50);
        panelProceso.setRoundTopLeft(50);
        panelProceso.setRoundTopRight(50);
        panelProceso.setLayout(null);

        lblOperacion.setBackground(new java.awt.Color(136, 138, 151));
        lblOperacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblOperacion.setForeground(new java.awt.Color(136, 138, 151));
        lblOperacion.setText("FACTURACION ELECTRONICA");
        lblOperacion.setName("lblOperacion"); // NOI18N
        panelProceso.add(lblOperacion);
        lblOperacion.setBounds(80, 0, 320, 50);

        lblIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/firefuel/resources/marca-de-verificacion (3).png"))); // NOI18N
        lblIcono.setToolTipText("");
        lblIcono.setName("lblIcono"); // NOI18N
        panelProceso.add(lblIcono);
        lblIcono.setBounds(20, 6, 36, 36);

        add(panelProceso);
        panelProceso.setBounds(10, 3, 410, 50);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblIcono;
    public javax.swing.JLabel lblOperacion;
    public com.firefuel.components.panelesPersonalizados.PanelRedondo panelProceso;
    // End of variables declaration//GEN-END:variables
}
