/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.firefuel;

import com.application.useCases.equipos.GetMacEquipoUseCase;
import com.application.useCases.equipos.IsAutorizedUseCase;
import com.bean.CredencialBean;
import com.controllers.ClientWSAsync;
import com.controllers.ControllerSync;
import com.controllers.NovusConstante;
import com.controllers.NovusUtils;
import com.dao.DAOException;
import com.dao.EquipoDao;
import com.google.gson.JsonObject;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import teclado.view.common.TecladoNumerico;

/**
 *
 * @author Admin
 */
public class RegistroEquipoView extends javax.swing.JFrame {

    public RegistroEquipoView() {
        initComponents();
        this.init();
    }

    void init() {
        NovusUtils.ajusteFuente(this.getContentPane().getComponents(), NovusConstante.EXTRABOLD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_keyboard = new TecladoNumerico();
        txt_estado = new javax.swing.JLabel();
        txt_code_identifier = new javax.swing.JTextField();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        title_view = new javax.swing.JLabel();
        jNotificacion = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 800));
        getContentPane().setLayout(null);
        getContentPane().add(pnl_keyboard);
        pnl_keyboard.setBounds(680, 140, 570, 470);

        txt_estado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txt_estado.setForeground(new java.awt.Color(153, 0, 0));
        txt_estado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_estado.setText("POR FAVOR INGRESAR LICENCIA");
        getContentPane().add(txt_estado);
        txt_estado.setBounds(60, 260, 570, 50);

        txt_code_identifier.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        txt_code_identifier.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_code_identifier.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 2, true));
        txt_code_identifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_code_identifierActionPerformed(evt);
            }
        });
        txt_code_identifier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_code_identifierKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_code_identifierKeyTyped(evt);
            }
        });
        getContentPane().add(txt_code_identifier);
        txt_code_identifier.setBounds(60, 150, 590, 70);

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/firefuel/resources/logoDevitech_3.png"))); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(10, 700, 110, 100);

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("INGRESE NUMERO DE LICENCIA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 90, 570, 40);

        title_view.setFont(new java.awt.Font("Terpel Sans", 1, 36)); // NOI18N
        title_view.setForeground(new java.awt.Color(255, 255, 255));
        title_view.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_view.setText("CONSULTA LICENCIA EQUIPO");
        title_view.setToolTipText("");
        getContentPane().add(title_view);
        title_view.setBounds(110, 0, 1080, 80);

        jNotificacion.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jNotificacion.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jNotificacion);
        jNotificacion.setBounds(150, 720, 530, 70);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/firefuel/resources/fndClientesLifeMiles.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 1280, 800);

        setSize(new java.awt.Dimension(1280, 800));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_code_identifierKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_code_identifierKeyTyped
        String caracteresAceptados = "[0-9]";
        NovusUtils.limitarCarateres(evt, txt_code_identifier, 20, jNotificacion, caracteresAceptados);
    }//GEN-LAST:event_txt_code_identifierKeyTyped

    private void txt_code_identifierActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_code_identifierActionPerformed
        fetchEstadoEquipo();
    }// GEN-LAST:event_txt_code_identifierActionPerformed

    private void txt_code_identifierKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txt_code_identifierKeyReleased
        String keyChar = evt.getKeyChar() + "";
    }// GEN-LAST:event_txt_code_identifierKeyReleased

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jNotificacion;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel pnl_keyboard;
    private javax.swing.JLabel title_view;
    private javax.swing.JTextField txt_code_identifier;
    private javax.swing.JLabel txt_estado;
    // End of variables declaration//GEN-END:variables
    private void fetchEstadoEquipo() {
        if (txt_code_identifier.getText().length() >= 10) {
            txt_estado.setText("VALIDANDO LICENCIA, POR FAVOR ESPERE...");

            setTimeout(1, () -> {
                TreeMap<String, String> header = new TreeMap<>();
                header.put("Authorization", "Basic cGFzc3BvcnR4OlQ0MUFYUWtYSjh6");
                header.put("Content-Type", "application/json");
                header.put("Accept", "*/*");
                header.put("dispositivo", "127.0.0.1");
                header.put("fecha", "2021-07-28T22:57:00-05");
                header.put("aplicacion", NovusConstante.APLICATION);
                try {
                    int timeout = 60000;
                    JsonObject json = new JsonObject();
                    json.addProperty("type", "new");
                    json.addProperty("code", txt_code_identifier.getText().trim());
                    ClientWSAsync client = new ClientWSAsync("VALIDADO LICENCIA",
                            NovusConstante.SECURE_END_POINT_VALIDAR_LICENCIA, NovusConstante.PUT, json, true, false,
                            header, timeout);
                    JsonObject response = client.esperaRespuesta();

                    if (response != null) {
                        NovusUtils.printLn(response.toString());
                        if (client.getStatus() == 200) {
                            NovusUtils.beep();
                            syncEstadoEquipo();
                        } else {
                            txt_estado.setText("LICENCIA NO VALIDA");
                        }
                    } else {
                        txt_estado.setText("LICENCIA NO VALIDA");
                    }
                } catch (Exception ex) {
                    txt_estado.setText("ERROR AL CONSULTAR LA LICENCIA");
                    NovusUtils.printLn(ex.getMessage());
                }
            });

        } else {
            txt_estado.setText("INGRESE UNA LICENCIA VALIDA");
            NovusUtils.beep();
        }

    }

    void syncEstadoEquipo() {
        try {
            txt_estado.setText("LICENCIA VALIDADA");
            EquipoDao dao = new EquipoDao();
            Main.credencial = new CredencialBean();
            Main.credencial.setId(1);
            Main.credencial.setEquipos_id(dao.findEquipoIdCore());
            Main.credencial.setEmpresas_id(dao.findEmpresaEquipoIdCore());
            GetMacEquipoUseCase getMacEquipoUseCase = new GetMacEquipoUseCase(Main.credencial.getEquipos_id());
            Main.credencial.setMac(getMacEquipoUseCase.execute());
            Main.credencial.setEmpresa(dao.findEmpresaCore(Main.credencial));
            Main.credencial.setAutorizado(new IsAutorizedUseCase(Main.credencial.getEquipos_id()).execute());
            Main.credencial.setPassword(" ");
            Main.credencial.setReferencia(" ");
            dao.createUpdateCredencial(Main.credencial);
            if (Main.credencial.getEquipos_id() > 0) {
                if (Main.credencial.isAutorizado()) {
                    this.setVisible(false);
                    long empresaId = dao.findEmpresaId();
                    if (empresaId == 0) {
                        SincronizarView sinc = new SincronizarView(this, true, true);
                        sinc.setVisible(true);
                    } else {
                        Main.info = new InfoViewController();
                        Main.info.setVisible(true);
                        ControllerSync sync = new ControllerSync();
                        sync.setDaemon(true);
                        sync.setPriority(Thread.MAX_PRIORITY);
                        sync.start();
                    }
                    this.dispose();
                } else {
                    txt_estado.setText("EQUIPO NO AUTORIZADO");
                }
            } else {
                txt_estado.setText("EQUIPO NO PRE-AUTORIZADO");
            }
        } catch (Exception e) {
            Logger.getLogger(RegistroEquipoView.class.getName()).log(Level.SEVERE, null, e);
            txt_estado.setText("ERROR AL REGISTRAR LA LICENCIA");
        } catch (DAOException ex) {
            txt_estado.setText("ERROR AL REGISTRAR LA LICENCIA");
            Logger.getLogger(RegistroEquipoView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setTimeout(int delay, Runnable runnable) {
        new Thread(() -> {
            try {
                Thread.sleep(delay * 1000);
                runnable.run();
            } catch (InterruptedException e) {
                NovusUtils.printLn("Interrupted.setTimeout" + e.getLocalizedMessage());
                // Restore interrupted state...
                Thread.currentThread().interrupt();
            }
        }).start();
    }

}
