/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.firefuel;

import com.application.commons.CtWacherParametrosEnum;
import com.application.useCases.transmisiones.BuscarTransmisionRemisionUseCase;
import com.application.useCases.wacherparametros.FindByParameterUseCase;
import com.controllers.NovusConstante;
import com.controllers.NovusUtils;
import com.dao.MovimientosDao;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.plaf.basic.BasicScrollBarUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Devitech
 */
public class VentasFE extends javax.swing.JFrame {
    FindByParameterUseCase findByParameterUseCase = new FindByParameterUseCase(CtWacherParametrosEnum.CODIGO.getColumnName(), "REMISION");

    SimpleDateFormat sdf = new SimpleDateFormat(NovusConstante.FORMAT_DATETIME_SQL);
    SimpleDateFormat sdf2 = new SimpleDateFormat(NovusConstante.FORMAT_BASIC_DATE);
    DecimalFormat df = new DecimalFormat(NovusConstante.FORMAT_MONEY);
    InfoViewController info;
    public long numeroVenta = 0;
    boolean facturar = false;
    int movimiento;

    public VentasFE() {
        initComponents();
        init();

    }

    public VentasFE(InfoViewController info) {
        this.info = info;
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMensaje = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(35);
        jTable1.setSelectionBackground(new java.awt.Color(255, 182, 0));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 92, 1260, 590));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ASIGNAR DATOS CLIENTES");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 540, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/firefuel/resources/botones/bt-danger-normal.png"))); // NOI18N
        jLabel2.setText("ASIGNAR CLIENTE");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, 330, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/firefuel/resources/btn_atras.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 70));

        jMensaje.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMensaje.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 730, 470, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/firefuel/resources/fndRumbo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
        cerrar();
    }//GEN-LAST:event_jLabel4MouseReleased

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        seleccionar(evt);
    }//GEN-LAST:event_jTable1MouseReleased

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        facturar();
    }//GEN-LAST:event_jLabel2MouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jMensaje;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void init() {
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        DefaultTableCellRenderer textRight;
        DefaultTableCellRenderer textCenter;
        textRight = new DefaultTableCellRenderer();
        textRight.setHorizontalAlignment(JLabel.RIGHT);
        textCenter = new DefaultTableCellRenderer();
        textCenter.setHorizontalAlignment(JLabel.CENTER);

        jTable1.setSelectionBackground(new Color(255, 182, 0));
        jTable1.setSelectionForeground(new Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color(186, 12, 47));
        headerRenderer.setForeground(new Color(255, 255, 255));
        jTable1.setFillsViewportHeight(true);
        headerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jScrollPane1.getVerticalScrollBar().setUI(new BasicScrollBarUI() {
            @Override
            protected void configureScrollBarColors() {
                this.thumbColor = new Color(186, 12, 47);
            }
        });
        jScrollPane1.getVerticalScrollBar().setBackground(new Color(255, 255, 255));
        jScrollPane1.getHorizontalScrollBar().setBackground(new Color(255, 255, 255));
        DefaultTableModel model = new DefaultTableModel() {
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        
        model.addColumn("ID");
        model.addColumn("FECHA FIN");
        model.addColumn("DESCRIPCION");
        model.addColumn("CANTIDAD");
        model.addColumn("PRECIO");
        model.addColumn("TOTAL");
        jTable1.setModel(model);
        jTable1.getTableHeader().setReorderingAllowed(false);
        for (int i = 0; i < jTable1.getModel().getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
            jTable1.getColumnModel().getColumn(i).setCellRenderer(textCenter);
        }

        cargarDatos();

    }

    private void cargarDatos() {
        MovimientosDao mdao = new MovimientosDao();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        DefaultTableModel defaultModel = (DefaultTableModel) jTable1.getModel();
        if (findByParameterUseCase.execute()) {
            //JsonArray datosRemision =  mdao.buscarTransminionRemision(2, "");
            JsonArray datosRemision = new BuscarTransmisionRemisionUseCase(2, "").execute();
            for (JsonElement elementosRemision : datosRemision) {
                JsonObject objVentas = elementosRemision.getAsJsonObject();
                JsonObject venta = objVentas.get("transaccion").getAsJsonObject();
                JsonArray detalleVenta = objVentas.get("detallesVenta").getAsJsonArray();
                long id =  objVentas.has("id_transmision") && !objVentas.get("id_transmision").isJsonNull()? objVentas.get("id_transmision").getAsLong() : 0L;
                for (JsonElement elementosDetalle : detalleVenta) {
                    JsonObject objDetalleVenta = elementosDetalle.getAsJsonObject();
                    defaultModel.addRow(new Object[]{
                        id + "",
                        venta.get("fechaTransaccion").getAsString(),
                        objDetalleVenta.get("nombreProducto").getAsString(),
                        objDetalleVenta.get("cantidadVenta").getAsFloat(),
                        "$ " + df.format(objDetalleVenta.get("precioProducto").getAsFloat()),
                        "$ " + df.format(objDetalleVenta.get("subTotalVenta").getAsFloat())
                    });
                }
            }
        } else {
            JsonArray listar = mdao.buscarTransminionFE(3, "");
            for (JsonElement elemt : listar) {
                JsonObject obj = elemt.getAsJsonObject();
                JsonObject ventaData = obj.get("venta").getAsJsonObject();
                JsonArray venta = obj.get("detalle").getAsJsonArray();
                long id = obj.get("id_transmision").getAsLong();
                for (JsonElement datosV : venta) {
                    JsonObject datosVenta = datosV.getAsJsonObject();
                    defaultModel.addRow(new Object[]{
                        id + "",
                        ventaData.get("create_date").getAsString().length() > 19 ? ventaData.get("create_date").getAsString().substring(0, 19) : ventaData.get("create_date").getAsString(),
                        datosVenta.get("producto_descripcion").getAsString(),
                        datosVenta.get("cantidad").getAsFloat(),
                        "$ " + df.format(datosVenta.get("precio").getAsFloat()),
                        "$ " + df.format(datosVenta.get("subtotal").getAsFloat())});
                }
            }
        }
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<TableModel>(jTable1.getModel()) {
            @Override
            public boolean isSortable(int column) {
                super.isSortable(column);
                return false;
            }
        };
        jTable1.setRowSorter(rowSorter);
    }

    // private void cargarDatos() {
    //     MovimientosDao mdao = new MovimientosDao();
    //     DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    //     model.getDataVector().removeAllElements();
    //     model.fireTableDataChanged();
    //     DefaultTableModel defaultModel = (DefaultTableModel) jTable1.getModel();
    //     if (mdao.remisionActiva()) {
    //         JsonArray datosRemision =  mdao.buscarTransminionRemision(2, "");
    //         for (JsonElement elementosRemision : datosRemision) {
    //             JsonObject objVentas = elementosRemision.getAsJsonObject();
    //             JsonObject venta = objVentas.get("transaccion").getAsJsonObject();
    //             JsonArray detalleVenta = objVentas.get("detallesVenta").getAsJsonArray();
    //             long id =  objVentas.has("id_transmision") && !objVentas.get("id_transmision").isJsonNull()? objVentas.get("id_transmision").getAsLong() : 0L;
    //             for (JsonElement elementosDetalle : detalleVenta) {
    //                 JsonObject objDetalleVenta = elementosDetalle.getAsJsonObject();
    //                 defaultModel.addRow(new Object[]{
    //                     id + "",
    //                     venta.get("fechaTransaccion").getAsString(),
    //                     objDetalleVenta.get("nombreProducto").getAsString(),
    //                     objDetalleVenta.get("cantidadVenta").getAsFloat(),
    //                     "$ " + df.format(objDetalleVenta.get("precioProducto").getAsFloat()),
    //                     "$ " + df.format(objDetalleVenta.get("subTotalVenta").getAsFloat())
    //                 });
    //             }
    //         }
    //     } else {
    //         JsonArray listar = mdao.buscarTransminionFE(3, "");
    //         for (JsonElement elemt : listar) {
    //             JsonObject obj = elemt.getAsJsonObject();
    //             JsonObject ventaData = obj.get("venta").getAsJsonObject();
    //             JsonArray venta = obj.get("detalle").getAsJsonArray();
    //             long id = obj.get("id_transmision").getAsLong();
    //             for (JsonElement datosV : venta) {
    //                 JsonObject datosVenta = datosV.getAsJsonObject();
    //                 defaultModel.addRow(new Object[]{
    //                     id + "",
    //                     ventaData.get("create_date").getAsString().length() > 19 ? ventaData.get("create_date").getAsString().substring(0, 19) : ventaData.get("create_date").getAsString(),
    //                     datosVenta.get("producto_descripcion").getAsString(),
    //                     datosVenta.get("cantidad").getAsFloat(),
    //                     "$ " + df.format(datosVenta.get("precio").getAsFloat()),
    //                     "$ " + df.format(datosVenta.get("subtotal").getAsFloat())});
    //             }
    //         }
    //     }
    //     TableRowSorter<TableModel> rowSorter = new TableRowSorter<TableModel>(jTable1.getModel()) {
    //         @Override
    //         public boolean isSortable(int column) {
    //             super.isSortable(column);
    //             return false;
    //         }
    //     };
    //     jTable1.setRowSorter(rowSorter);
    // }

    void seleccionar(MouseEvent evt) {
        int r = jTable1.getSelectedRow();
        if (r >= 0) {
            int seleccionar;
            seleccionar = jTable1.rowAtPoint(evt.getPoint());
            String numero = String.valueOf(jTable1.getValueAt(seleccionar, 0));
            numeroVenta = Long.parseLong(numero);

            facturar = true;
        } else {
            facturar = false;
        }
    }

    private void cerrar() {
        this.info.setVisible(true);
        dispose();

    }

    private void facturar() {
        if (facturar) {
            ClienteFacturaElectronica cliente = new ClienteFacturaElectronica(info, true, numeroVenta, true, this);
            NovusUtils.printLn("abriendo la vista de facturacio electronica desde -> " + VentasFE.class.getName());
            cliente.setVisible(true);
            dispose();
        } else {
            jMensaje.setText("NO HAY VENTAS SELECCIONADAS");
        }

    }
}
