/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.firefuel.componentes.sap;

import com.firefuel.components.panelesPersonalizados.BordesRedondos;
import java.awt.Color;

/**
 *
 * @author Devitech
 */
public class ItemTanques extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public ItemTanques() {
        initComponents();
        pnlContenedor.setBorder(new BordesRedondos(new Color(204, 0, 0), 30));
        Numero.setName("numero");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        pnlContenedorNumero = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        Numero = new javax.swing.JLabel();
        lblTittuloCantidad = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblNombreTanque = new javax.swing.JLabel();
        lblTituloTanque = new javax.swing.JLabel();
        btnEliminar = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        lblEliminar = new javax.swing.JLabel();

        setLayout(null);

        pnlContenedor.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenedor.setName("pnlContenedor"); // NOI18N
        pnlContenedor.setRoundBottomLeft(30);
        pnlContenedor.setRoundBottomRight(30);
        pnlContenedor.setRoundTopLeft(30);
        pnlContenedor.setRoundTopRight(30);
        pnlContenedor.setLayout(null);

        pnlContenedorNumero.setBackground(new java.awt.Color(204, 0, 0));
        pnlContenedorNumero.setName("pnlContenedorNumero"); // NOI18N
        pnlContenedorNumero.setRoundBottomLeft(30);
        pnlContenedorNumero.setRoundTopLeft(30);
        pnlContenedorNumero.setLayout(null);

        Numero.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Numero.setForeground(new java.awt.Color(255, 255, 255));
        Numero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Numero.setText("1");
        Numero.setName("Numero"); // NOI18N
        pnlContenedorNumero.add(Numero);
        Numero.setBounds(0, 0, 70, 70);

        pnlContenedor.add(pnlContenedorNumero);
        pnlContenedorNumero.setBounds(0, 0, 70, 70);

        lblTittuloCantidad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTittuloCantidad.setForeground(new java.awt.Color(204, 0, 0));
        lblTittuloCantidad.setText("CANTIDAD");
        lblTittuloCantidad.setName("lblTittuloCantidad"); // NOI18N
        pnlContenedor.add(lblTittuloCantidad);
        lblTittuloCantidad.setBounds(390, 5, 110, 30);

        lblCantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(0, 0, 0));
        lblCantidad.setText("20000 GL");
        lblCantidad.setName("lblCantidad"); // NOI18N
        pnlContenedor.add(lblCantidad);
        lblCantidad.setBounds(390, 35, 100, 30);

        lblNombreTanque.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombreTanque.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreTanque.setText("Tanque corriente 1 7% oxigenada");
        lblNombreTanque.setName("lblNombreTanque"); // NOI18N
        pnlContenedor.add(lblNombreTanque);
        lblNombreTanque.setBounds(75, 35, 310, 30);

        lblTituloTanque.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloTanque.setForeground(new java.awt.Color(204, 0, 0));
        lblTituloTanque.setText("TANQUE");
        lblTituloTanque.setName("lblTituloTanque"); // NOI18N
        pnlContenedor.add(lblTituloTanque);
        lblTituloTanque.setBounds(75, 5, 80, 30);

        btnEliminar.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminar.setName("btnEliminar"); // NOI18N
        btnEliminar.setRoundBottomLeft(50);
        btnEliminar.setRoundBottomRight(50);
        btnEliminar.setRoundTopLeft(50);
        btnEliminar.setRoundTopRight(50);
        btnEliminar.setLayout(null);

        lblEliminar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEliminar.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminar.setText("X");
        lblEliminar.setName("lblEliminar"); // NOI18N
        btnEliminar.add(lblEliminar);
        lblEliminar.setBounds(0, 0, 50, 50);

        pnlContenedor.add(btnEliminar);
        btnEliminar.setBounds(520, 10, 50, 50);

        add(pnlContenedor);
        pnlContenedor.setBounds(0, 0, 580, 70);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Numero;
    private com.firefuel.components.panelesPersonalizados.PanelRedondo btnEliminar;
    public javax.swing.JLabel lblCantidad;
    public javax.swing.JLabel lblEliminar;
    public javax.swing.JLabel lblNombreTanque;
    private javax.swing.JLabel lblTittuloCantidad;
    private javax.swing.JLabel lblTituloTanque;
    public com.firefuel.components.panelesPersonalizados.PanelRedondo pnlContenedor;
    private com.firefuel.components.panelesPersonalizados.PanelRedondo pnlContenedorNumero;
    // End of variables declaration//GEN-END:variables
}
