/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.firefuel.componentes.notificaciones.error;

import com.google.gson.JsonArray;

/**
 *
 * @author Devitech
 */
public class ContenedorFechas extends javax.swing.JPanel {

    RenderizacionError renderizacionError;
    JsonArray data;

    public ContenedorFechas(RenderizacionError renderizacionError, JsonArray data) {
        initComponents();
        this.renderizacionError = renderizacionError;
        this.data = data;
        init();

    }

    private void init() {
        RenderizacionContenedorFechas contenedorFechas = new RenderizacionContenedorFechas(this, this.renderizacionError);
        contenedorFechas.renderizarHoras(data);
        contenedorFechas.scrollPanelPerosonalizado(scrollContenedorPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollContenedorPanel = new javax.swing.JScrollPane();
        pnlContenedorFechas = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        scrollContenedorPanel.setBorder(null);
        scrollContenedorPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollContenedorPanel.setMinimumSize(new java.awt.Dimension(300, 354));
        scrollContenedorPanel.setName("scrollContenedorPanel"); // NOI18N
        scrollContenedorPanel.setPreferredSize(new java.awt.Dimension(300, 354));

        pnlContenedorFechas.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenedorFechas.setMinimumSize(new java.awt.Dimension(340, 350));
        pnlContenedorFechas.setName("pnlContenedorFechas"); // NOI18N
        pnlContenedorFechas.setPreferredSize(new java.awt.Dimension(340, 350));
        scrollContenedorPanel.setViewportView(pnlContenedorFechas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollContenedorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollContenedorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel pnlContenedorFechas;
    public javax.swing.JScrollPane scrollContenedorPanel;
    // End of variables declaration//GEN-END:variables
}
