/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.firefuel.componentes.notificaciones.error;

/**
 *
 * @author Devitech
 */
public class FechasPadres extends javax.swing.JPanel {

    /**
     * Creates new form FechasPadres
     */
    public FechasPadres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlItem = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        lblFecha = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        setLayout(null);

        pnlItem.setBackground(new java.awt.Color(229, 230, 232));
        pnlItem.setName("pnlItem"); // NOI18N
        pnlItem.setRoundBottomLeft(30);
        pnlItem.setRoundBottomRight(30);
        pnlItem.setRoundTopLeft(30);
        pnlItem.setRoundTopRight(30);
        pnlItem.setLayout(null);

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(102, 102, 102));
        lblFecha.setText("HOY");
        lblFecha.setName("lblFecha"); // NOI18N
        pnlItem.add(lblFecha);
        lblFecha.setBounds(16, 6, 310, 26);

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/firefuel/resources/flecha.png"))); // NOI18N
        lblImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblImage.setName("lblImage"); // NOI18N
        pnlItem.add(lblImage);
        lblImage.setBounds(280, 8, 46, 26);

        add(pnlItem);
        pnlItem.setBounds(6, 6, 335, 38);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lblFecha;
    public javax.swing.JLabel lblImage;
    public com.firefuel.components.panelesPersonalizados.PanelRedondo pnlItem;
    // End of variables declaration//GEN-END:variables
}
