/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.firefuel.componentes.notificaciones.error;

/**
 *
 * @author Devitech
 */
public class InformacionError extends javax.swing.JPanel {

    /**
     * Creates new form InformacionError
     */
    public InformacionError() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorInformacionError = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        lblInformacion = new javax.swing.JLabel();
        pnlContenedorInformacionError = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        lblIconoInformacionError = new javax.swing.JLabel();
        panelRedondo1 = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        lblTitulo = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();

        setBackground(new java.awt.Color(229, 230, 232));

        contenedorInformacionError.setBackground(new java.awt.Color(244, 244, 244));
        contenedorInformacionError.setName("contenedorInformacionError"); // NOI18N
        contenedorInformacionError.setRoundBottomLeft(40);
        contenedorInformacionError.setRoundBottomRight(40);
        contenedorInformacionError.setRoundTopLeft(40);
        contenedorInformacionError.setRoundTopRight(40);

        lblInformacion.setBackground(new java.awt.Color(0, 0, 0));
        lblInformacion.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblInformacion.setForeground(new java.awt.Color(102, 102, 102));
        lblInformacion.setText("<html><meta charset=\"UTF-8\">Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno</html>");
        lblInformacion.setToolTipText("");
        lblInformacion.setName("lblInformacion"); // NOI18N

        pnlContenedorInformacionError.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenedorInformacionError.setName("pnlContenedorInformacionError"); // NOI18N
        pnlContenedorInformacionError.setRoundBottomLeft(100);
        pnlContenedorInformacionError.setRoundBottomRight(100);
        pnlContenedorInformacionError.setRoundTopLeft(100);
        pnlContenedorInformacionError.setRoundTopRight(100);

        lblIconoInformacionError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/firefuel/resources/Estado_Error_Small.png"))); // NOI18N
        lblIconoInformacionError.setName("lblIconoInformacionError"); // NOI18N

        javax.swing.GroupLayout pnlContenedorInformacionErrorLayout = new javax.swing.GroupLayout(pnlContenedorInformacionError);
        pnlContenedorInformacionError.setLayout(pnlContenedorInformacionErrorLayout);
        pnlContenedorInformacionErrorLayout.setHorizontalGroup(
            pnlContenedorInformacionErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenedorInformacionErrorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconoInformacionError)
                .addContainerGap())
        );
        pnlContenedorInformacionErrorLayout.setVerticalGroup(
            pnlContenedorInformacionErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenedorInformacionErrorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconoInformacionError)
                .addContainerGap())
        );

        panelRedondo1.setBackground(new java.awt.Color(204, 0, 0));
        panelRedondo1.setName("panelRedondo1"); // NOI18N
        panelRedondo1.setRoundBottomLeft(30);
        panelRedondo1.setRoundBottomRight(30);
        panelRedondo1.setRoundTopLeft(30);
        panelRedondo1.setRoundTopRight(30);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Informacion");
        lblTitulo.setName("lblTitulo"); // NOI18N

        lblHora.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHora.setText("100:00 am ");
        lblHora.setName("lblHora"); // NOI18N

        javax.swing.GroupLayout panelRedondo1Layout = new javax.swing.GroupLayout(panelRedondo1);
        panelRedondo1.setLayout(panelRedondo1Layout);
        panelRedondo1Layout.setHorizontalGroup(
            panelRedondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondo1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelRedondo1Layout.setVerticalGroup(
            panelRedondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRedondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contenedorInformacionErrorLayout = new javax.swing.GroupLayout(contenedorInformacionError);
        contenedorInformacionError.setLayout(contenedorInformacionErrorLayout);
        contenedorInformacionErrorLayout.setHorizontalGroup(
            contenedorInformacionErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorInformacionErrorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContenedorInformacionError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorInformacionErrorLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(panelRedondo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        contenedorInformacionErrorLayout.setVerticalGroup(
            contenedorInformacionErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorInformacionErrorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRedondo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenedorInformacionErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorInformacionErrorLayout.createSequentialGroup()
                        .addComponent(pnlContenedorInformacionError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addComponent(lblInformacion))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorInformacionError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorInformacionError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.firefuel.components.panelesPersonalizados.PanelRedondo contenedorInformacionError;
    public javax.swing.JLabel lblHora;
    public javax.swing.JLabel lblIconoInformacionError;
    public javax.swing.JLabel lblInformacion;
    public javax.swing.JLabel lblTitulo;
    private com.firefuel.components.panelesPersonalizados.PanelRedondo panelRedondo1;
    public com.firefuel.components.panelesPersonalizados.PanelRedondo pnlContenedorInformacionError;
    // End of variables declaration//GEN-END:variables
}
