/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.firefuel.componentes.anulacion;

import com.firefuel.components.panelesPersonalizados.BordesRedondos;
import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class ItemProducto extends javax.swing.JPanel {

    /**
     * Creates new form itemProducto
     */
    public ItemProducto() {
        initComponents();
        pnlItem.setBorder(new BordesRedondos(new Color(153, 0, 0), 20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlItem = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        lblProducto = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        pnlBoton = new com.firefuel.components.panelesPersonalizados.PanelRedondo();
        lblAccion = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(570, 70));

        pnlItem.setBackground(new java.awt.Color(255, 255, 255));
        pnlItem.setRoundBottomLeft(20);
        pnlItem.setRoundBottomRight(20);
        pnlItem.setRoundTopLeft(20);
        pnlItem.setRoundTopRight(20);
        pnlItem.setLayout(null);

        lblProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblProducto.setForeground(new java.awt.Color(51, 51, 51));
        lblProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProducto.setText("Producto");
        pnlItem.add(lblProducto);
        lblProducto.setBounds(6, 14, 230, 44);

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(51, 51, 51));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("Valor");
        pnlItem.add(lblTotal);
        lblTotal.setBounds(346, 14, 145, 44);

        lblCantidad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(51, 51, 51));
        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantidad.setText("Cantidad");
        pnlItem.add(lblCantidad);
        lblCantidad.setBounds(242, 14, 98, 44);

        pnlBoton.setBackground(new java.awt.Color(153, 0, 0));
        pnlBoton.setRoundBottomLeft(70);
        pnlBoton.setRoundBottomRight(70);
        pnlBoton.setRoundTopLeft(70);
        pnlBoton.setRoundTopRight(70);

        lblAccion.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblAccion.setForeground(new java.awt.Color(255, 255, 255));
        lblAccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccion.setText("+");

        javax.swing.GroupLayout pnlBotonLayout = new javax.swing.GroupLayout(pnlBoton);
        pnlBoton.setLayout(pnlBotonLayout);
        pnlBotonLayout.setHorizontalGroup(
            pnlBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAccion, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        pnlBotonLayout.setVerticalGroup(
            pnlBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pnlItem.add(pnlBoton);
        pnlBoton.setBounds(503, 6, 60, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(pnlItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlItem, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lblAccion;
    public javax.swing.JLabel lblCantidad;
    public javax.swing.JLabel lblProducto;
    public javax.swing.JLabel lblTotal;
    public com.firefuel.components.panelesPersonalizados.PanelRedondo pnlBoton;
    public com.firefuel.components.panelesPersonalizados.PanelRedondo pnlItem;
    // End of variables declaration//GEN-END:variables
}
